### ISSUE TITLE
Make it possible to print the schema with landscape orientation

### ISSUE THREAD

**Issue by evilaliv3** [eralchemy/eralchemy#41] opened 2018-01-19 13:20 UTC
It would be nice to add a feature for changing the orientation of the print layout.

Depending on the schema in fact sometimes a landscape orientation could look nicer and user would be able to do a test of the print and choose the best option for their schema,

**Comment by maurerle** [comment] 2024-07-09 05:56
I think it would still be useful to have a method to set `graph [rankdir=TB];` in the `DOT_GRAPH_BEGINNING` instead of the default Left to Right - even though other methods to create this (mermaid/markdown) exist

**Comment by maurerle** [comment] 2024-07-09 05:58
Though this is a duplicate of #63 then :D so I am closing it.

**Closed by maurerle** 2024-07-09 05:58 UTC
