### ISSUE TITLE
reading relationships from Postgresql database

### ISSUE THREAD

**Issue by johny-b** [eralchemy/eralchemy#53] opened 2018-10-04 17:08 UTC
Hello,

I wanted to create .er file based on schema in Postgresql database.
It works well for tables, but ignores relationships. 

Example script
```
psql t1 -c "CREATE SCHEMA t1;
            CREATE TABLE  t1.parent(id INTEGER PRIMARY KEY);
            CREATE TABLE  t1.child (id INTEGER PRIMARY KEY,
                                   parent_id INTEGER REFERENCES t1.parent(id) NOT NULL)"
eralchemy -i 'postgresql+psycopg2:///t1' -s t1 -o t1.er
cat t1.er
```

yields output
```
[t1.parent]
    *id {label:"INTEGER"}
[t1.child]
    *id {label:"INTEGER"}
    parent_id {label:"INTEGER"}
```
ignoring FOREIGN KEY constraint. Is it intended? 

I'm using PostgreSQL 9.6.10 on Ubuntu 18.04 and ERAlchemy version 1.2.10.

**Comment by dominikclariant** [comment] 2019-03-04 13:12
Same problem for me. It ignores relations between tables when my input is an existing postgres instance.

**Comment by renatolsromao** [comment] 2019-05-10 19:47
Same problem here!

**Comment by lorarjohns** [comment] 2020-11-26 00:11
I have this issue as well.

**Comment by maurerle** [comment] 2024-07-07 10:08
As the changes from my fork are now merged here, and I could not reproduce this issue, I'll close it now.

**Closed by maurerle** 2024-07-07 10:08 UTC
