### ISSUE TITLE
Add version info of required compatible Graphviz on Windows

### ISSUE THREAD

**Issue by makeevolution** [eralchemy/eralchemy#90] opened 2022-05-27 17:03 UTC
Maybe consider adding on the readme.MD info of the version of Graphviz that is compatible, especially for Windows. I used the latest version (3.0.0) and installing pygraphviz (from the requirements.txt) didn't work. The latest version that works for Windows is 2.49.0.

**Comment by maurerle** [comment] 2022-10-10 11:00
Hi,
so the latest pygraphviz does not work/install on windows correctly?
can you confirm this on my fork and open an issue if the install on windows has problems?

https://github.com/maurerle/eralchemy2with

**Comment by maurerle** [comment] 2024-07-09 06:34
Duplicate of #47 - we should take a look if eralchemy currently works on windows with pygraphviz or if workarounds are still needed.

**Comment by kasium** [comment] 2024-07-12 17:27
@maurerle I checked the issue and it seems that pygraphviz provides a good guide how to install it on windows: https://pygraphviz.github.io/documentation/stable/install.html#windows. With this guide I could use the following combination

- latest graphviz (12.0,0)
- latest pygraphviz (1.13)
- latest eralchemy2 (1.41)
- latest eralchemy (1.2.10)

using python3.12.

To be honest, installation issues of pygraphviz are not the fault of eralchemy or eralchemy2. It's challenging but I don't see this in our domain. We could however explorer alternatives to pygraphviz but not sure about this.

I would recommend to close this issue. #47 needs further checks from my side

**Comment by maurerle** [comment] 2024-07-13 07:59
We could add a hint to install instructions for (py)graphviz to the readme, but currently, no version info is required as the latest version is working fine.

**Closed by maurerle** 2024-07-13 07:59 UTC
